all:
	rm -rf distfiles
	mkdir -p distfiles
	env FLAG="ACSC{okay_you_must_be_over_twice_as_powerful_as_the_DSA}" python3 challenge/task.py > distfiles/output.txt
	cp challenge/task.py distfiles/task.py
