name: pdf_converter
description: A simple image to pdf converter
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_multipart: ^1.0.0
  path: ^1.8.3
  pdf: ^3.8.4
  image: ^3.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
