version: '3'
services:
  evalbox:
    build:
      context: .
    working_dir: /home/ctf
    container_name: evalbox
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9341:9999"
    restart: always
