version: '3'
services:
  snake:
    build:
      context: .
    working_dir: /home/ctf
    container_name: snake
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "4444:4444"
    restart: always